spring:
  config:
    import:
      - application-local.yml

  jpa:
    hibernate:
      ddl-auto: create # create 경우 시작시 table drop-create 함
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

server:
  port: 8001
