server:
  port: 8001

spring:
  h2:
    console:
      enabled: true
  config:
    import:
#      - application-local.yml # Notion 코드공유 확인
      - application-jwt.yml
      - application-dev.yml # Notion 코드공유 확인

  jpa:
    hibernate:
      ddl-auto: create # 매번 table 초기화 됨
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  profiles:
    include: jwt

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

springdoc:
  swagger-ui:
    path: swagger.html
  version: v1
  paths-to-match:
    - /api/**